### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by MohamadSH** [spatie/checkout#2]
Hi ,
Thank you very much for this package but unfortunately I got this error during the installing through composer command :
`  Problem 1               
                                                            
    - Conclusion: remove laravel/framework v5.3.26     
                               
    - Conclusion: don't install laravel/framework v5.3.26   
                          
    - spatie/checkout 2.0.0 requires illuminate/session ~5.1.0|~5.2.0 -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41,v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32,v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].                                                                              
    - spatie/checkout 2.0.1 requires illuminate/session ~5.1.0|~5.2.0 -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].                                                                              
    - spatie/checkout 2.0.2 requires illuminate/session ~5.1.0|~5.2.0 -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].`

I hope you can help me with this . I suppose I can't use it with Laravel v5.3.26

**Comment by freekmurze** [comment]
If tagged a new version that is L5.3 compatible. Try running `composer require spatie/checkout` again.
